import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { CopyToClipboard } from 'react-copy-to-clipboard';

const EmbedCode = ({ onClose }) => {
  const { currentUser } = useAuth();
  const [code, setCode] = useState('');
  const [copied, setCopied] = useState(false);
  const [domain, setDomain] = useState('');

  useEffect(() => {
    if (currentUser) {
      // In a real app, this would be generated by the backend
      const clientId = currentUser.id;
      const signature = `signature_${Math.random().toString(36).substr(2, 12)}`;
      
      const embedCode = `<div id="chatbot-widget"></div>
<script>
  window.chatbotConfig = {
    clientId: "${clientId}",
    domain: "${domain || 'yourdomain.com'}",
    signature: "${signature}"
  };
  (function() {
    var d = document, s = d.createElement('script');
    s.src = 'https://yourdomain.com/widget.js';
    s.async = true;
    d.head.appendChild(s);
  })();
</script>`;
      
      setCode(embedCode);
    }
  }, [currentUser, domain]);

  const handleCopy = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl">
        <div className="p-6">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-bold text-gray-800">Embed Chatbot on Your Website</h2>
            <button 
              onClick={onClose}
              className="text-gray-500 hover:text-gray-700"
            >
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          
          <div className="mb-6">
            <label htmlFor="domain" className="block text-sm font-medium text-gray-700 mb-1">
              Your Website Domain
            </label>
            <input
              type="text"
              id="domain"
              className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              placeholder="example.com"
              value={domain}
              onChange={(e) => setDomain(e.target.value)}
            />
            <p className="mt-1 text-sm text-gray-500">
              This domain will be whitelisted for the chatbot to work
            </p>
          </div>
          
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Embed Code
            </label>
            <div className="relative">
              <pre className="bg-gray-800 text-gray-200 p-4 rounded-md overflow-x-auto text-sm">
                {code}
              </pre>
              <CopyToClipboard text={code} onCopy={handleCopy}>
                <button className="absolute top-2 right-2 bg-blue-600 text-white px-3 py-1 rounded-md text-sm hover:bg-blue-700">
                  {copied ? 'Copied!' : 'Copy Code'}
                </button>
              </CopyToClipboard>
            </div>
          </div>
          
          <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-4">
            <div className="flex">
              <div className="flex-shrink-0">
                <svg className="h-5 w-5 text-yellow-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
              </div>
              <div className="ml-3">
                <p className="text-sm text-yellow-700">
                  For security reasons, the chatbot will only work on the domain you specify above.
                  Make sure to update this if you change your website domain.
                </p>
              </div>
            </div>
          </div>
          
          <div className="flex justify-end">
            <button
              onClick={onClose}
              className="bg-gray-200 text-gray-800 px-4 py-2 rounded-md hover:bg-gray-300 mr-2"
            >
              Close
            </button>
            <button
              onClick={onClose}
              className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EmbedCode;